In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df = pd.read_csv("netflix_data_storytelling.csv")
df

,Show_ID,Title,Type,Country,Release_Year,Duration,Genre,IMDb_Rating,Views_Millions,Age_Rating,Is_Hit
0,S001,Dark,Movie,UK,2018,97 min,Action,8.3,125.7,18+,Yes
1,S002,Sacred Games Returns,Movie,USA,2016,107 min,Comedy,6.0,84.2,18+,No
2,S003,Extraction Returns,Series,India,2024,3 Seasons,Comedy,8.6,43.8,13+,No
3,S004,Kota Factory 3,Movie,India,2020,93 min,Drama,5.4,34.8,16+,No
4,S005,Queen's Gambit 3,Series,USA,2023,1 Seasons,Documentary,9.4,100.4,18+,Yes
...,...,...,...,...,...,...,...,...,...,...,...
495,S496,Kota Factory 2,Movie,USA,2022,84 min,Romance,8.9,115.4,13+,Yes
496,S497,Sacred Games Reborn,Movie,India,2021,146 min,Action,6.9,125.0,18+,No
497,S498,The Witcher Reborn,Series,France,2021,3 Seasons,Sci-Fi,7.7,124.1,18+,Yes
498,S499,Delhi Crime,Series,India,2022,2 Seasons,Comedy,9.1,56.9,18+,No
499,S500,Narcos Reborn,Movie,India,2015,146 min,Drama,5.5,28.1,18+,No

In [ ]:
df["Duration_num"] = df["Duration"].str.extract(r'(\\d+)').astype(float)
df["Duration_type"] = df["Duration"].str.contains('Season').map({True:'Season',False:'Minutes'})
df['Is_Hit_Bin']=(df['Is_Hit']=='Yes').astype(int)

In [ ]:
df

,Show_ID,Title,Type,Country,Release_Year,Duration,Genre,IMDb_Rating,Views_Millions,Age_Rating,Is_Hit,Duration_num,Duration_type,Is_Hit_Bin
0,S001,Dark,Movie,UK,2018,97 min,Action,8.3,125.7,18+,Yes,NaN,Minutes,1
1,S002,Sacred Games Returns,Movie,USA,2016,107 min,Comedy,6.0,84.2,18+,No,NaN,Minutes,0
2,S003,Extraction Returns,Series,India,2024,3 Seasons,Comedy,8.6,43.8,13+,No,NaN,Season,0
3,S004,Kota Factory 3,Movie,India,2020,93 min,Drama,5.4,34.8,16+,No,NaN,Minutes,0
4,S005,Queen's Gambit 3,Series,USA,2023,1 Seasons,Documentary,9.4,100.4,18+,Yes,NaN,Season,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,S496,Kota Factory 2,Movie,USA,2022,84 min,Romance,8.9,115.4,13+,Yes,NaN,Minutes,1
496,S497,Sacred Games Reborn,Movie,India,2021,146 min,Action,6.9,125.0,18+,No,NaN,Minutes,0
497,S498,The Witcher Reborn,Series,France,2021,3 Seasons,Sci-Fi,7.7,124.1,18+,Yes,NaN,Season,1
498,S499,Delhi Crime,Series,India,2022,2 Seasons,Comedy,9.1,56.9,18+,No,NaN,Season,0
499,S500,Narcos Reborn,Movie,India,2015,146 min,Drama,5.5,28.1,18+,No,NaN,Minutes,0

In [ ]:
#which genre gets the most view
genre_views = df.groupby('Genre')['Views_Millions'].mean()
genre_views

Genre
Action         97.042169
Comedy         96.403659
Documentary    85.384848
Drama          89.670149
Romance        95.167857
Sci-Fi         97.960274
Thriller       95.234247
Name: Views_Millions, dtype: float64